/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SettingsLazyImport = createFileRoute('/settings')()
const PuntoDeVentaLazyImport = createFileRoute('/punto-de-venta')()
const ProductsLazyImport = createFileRoute('/products')()
const ProductosLazyImport = createFileRoute('/productos')()
const PosLazyImport = createFileRoute('/pos')()
const DiarioDeCajaLazyImport = createFileRoute('/diario-de-caja')()
const DashboardLazyImport = createFileRoute('/dashboard')()
const CustomersLazyImport = createFileRoute('/customers')()
const ConfiguracionLazyImport = createFileRoute('/configuracion')()
const ClientesLazyImport = createFileRoute('/clientes')()
const CashRegisterLazyImport = createFileRoute('/cash-register')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SettingsLazyRoute = SettingsLazyImport.update({
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))

const PuntoDeVentaLazyRoute = PuntoDeVentaLazyImport.update({
  path: '/punto-de-venta',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/punto-de-venta.lazy').then((d) => d.Route),
)

const ProductsLazyRoute = ProductsLazyImport.update({
  path: '/products',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/products.lazy').then((d) => d.Route))

const ProductosLazyRoute = ProductosLazyImport.update({
  path: '/productos',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/productos.lazy').then((d) => d.Route))

const PosLazyRoute = PosLazyImport.update({
  path: '/pos',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/pos.lazy').then((d) => d.Route))

const DiarioDeCajaLazyRoute = DiarioDeCajaLazyImport.update({
  path: '/diario-de-caja',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/diario-de-caja.lazy').then((d) => d.Route),
)

const DashboardLazyRoute = DashboardLazyImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))

const CustomersLazyRoute = CustomersLazyImport.update({
  path: '/customers',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/customers.lazy').then((d) => d.Route))

const ConfiguracionLazyRoute = ConfiguracionLazyImport.update({
  path: '/configuracion',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/configuracion.lazy').then((d) => d.Route))

const ClientesLazyRoute = ClientesLazyImport.update({
  path: '/clientes',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/clientes.lazy').then((d) => d.Route))

const CashRegisterLazyRoute = CashRegisterLazyImport.update({
  path: '/cash-register',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cash-register.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cash-register': {
      id: '/cash-register'
      path: '/cash-register'
      fullPath: '/cash-register'
      preLoaderRoute: typeof CashRegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesLazyImport
      parentRoute: typeof rootRoute
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionLazyImport
      parentRoute: typeof rootRoute
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersLazyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLazyImport
      parentRoute: typeof rootRoute
    }
    '/diario-de-caja': {
      id: '/diario-de-caja'
      path: '/diario-de-caja'
      fullPath: '/diario-de-caja'
      preLoaderRoute: typeof DiarioDeCajaLazyImport
      parentRoute: typeof rootRoute
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosLazyImport
      parentRoute: typeof rootRoute
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosLazyImport
      parentRoute: typeof rootRoute
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsLazyImport
      parentRoute: typeof rootRoute
    }
    '/punto-de-venta': {
      id: '/punto-de-venta'
      path: '/punto-de-venta'
      fullPath: '/punto-de-venta'
      preLoaderRoute: typeof PuntoDeVentaLazyImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  CashRegisterLazyRoute,
  ClientesLazyRoute,
  ConfiguracionLazyRoute,
  CustomersLazyRoute,
  DashboardLazyRoute,
  DiarioDeCajaLazyRoute,
  PosLazyRoute,
  ProductosLazyRoute,
  ProductsLazyRoute,
  PuntoDeVentaLazyRoute,
  SettingsLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cash-register",
        "/clientes",
        "/configuracion",
        "/customers",
        "/dashboard",
        "/diario-de-caja",
        "/pos",
        "/productos",
        "/products",
        "/punto-de-venta",
        "/settings"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/cash-register": {
      "filePath": "cash-register.lazy.tsx"
    },
    "/clientes": {
      "filePath": "clientes.lazy.tsx"
    },
    "/configuracion": {
      "filePath": "configuracion.lazy.tsx"
    },
    "/customers": {
      "filePath": "customers.lazy.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.lazy.tsx"
    },
    "/diario-de-caja": {
      "filePath": "diario-de-caja.lazy.tsx"
    },
    "/pos": {
      "filePath": "pos.lazy.tsx"
    },
    "/productos": {
      "filePath": "productos.lazy.tsx"
    },
    "/products": {
      "filePath": "products.lazy.tsx"
    },
    "/punto-de-venta": {
      "filePath": "punto-de-venta.lazy.tsx"
    },
    "/settings": {
      "filePath": "settings.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
